SET GLOBAL FOREIGN_KEY_CHECKS=1;

USE mysql;
DROP DATABASE a;
USE mysql;
CREATE DATABASE a ; 
USE a;

CREATE TABLE entity_type (	
	id SMALLINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	title VARCHAR(255) NOT NULL UNIQUE);

INSERT entity_type (id, title) VALUES (1, 'Заказ'), (2, 'Комплект'), (3, 'Модуль'), (4, 'Корпус'), (5, 'Узел');

CREATE TABLE entity (
	id BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	title VARCHAR(255) NOT NULL,
	id_type SMALLINT NOT NULL,
	specification VARCHAR(255) NOT NULL,
	marking TINYINT NOT NULL DEFAULT 0 CHECK(marking >= 0 AND marking < 4),
	enumerable BOOL NOT NULL DEFAULT true,
	note VARCHAR(1023) NOT NULL,
	UNIQUE (id_type, title),
	FOREIGN KEY (id_type) REFERENCES entity_type(id) ON DELETE RESTRICT ON UPDATE CASCADE);

CREATE TABLE entity_rec (
	id_parent BIGINT NOT NULL,
	id_child BIGINT NOT NULL,
	count INT NOT NULL,
	PRIMARY KEY (id_parent, id_child),
	FOREIGN KEY (id_parent) REFERENCES entity (id) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (id_child) REFERENCES entity (id) ON DELETE RESTRICT ON UPDATE CASCADE);

CREATE TABLE marking (
	id BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY);

CREATE TABLE marking_line (
	id_marking BIGINT NOT NULL,
	id_entity BIGINT NOT NULL,
	number TINYINT NOT NULL,
	PRIMARY KEY (id_marking, id_entity),
	FOREIGN KEY (id_marking) REFERENCES marking(id) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (id_entity) REFERENCES entity(id) ON DELETE RESTRICT ON UPDATE CASCADE);

CREATE TABLE marked_detail (
	id BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	id_marking BIGINT NOT NULL,
	mark VARCHAR(15) NOT NULL,
	id_parent BIGINT NULL,
	UNIQUE(id_marking, mark),
	FOREIGN KEY (id_marking) REFERENCES marking(id) ON DELETE RESTRICT ON UPDATE CASCADE,
	FOREIGN KEY (id_parent) REFERENCES marked_detail(id) ON DELETE RESTRICT ON UPDATE CASCADE);

CREATE TABLE person (
	id SMALLINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	name VARCHAR(63) NOT NULL UNIQUE);

CREATE TABLE status_type (	
	id SMALLINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	title VARCHAR(255) NOT NULL UNIQUE);
	
CREATE TABLE status (	
	id BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	day DATE NOT NULL,
	id_type SMALLINT NOT NULL,
	id_person SMALLINT NULL,
	note VARCHAR(63) NOT NULL,
	FOREIGN KEY (id_person) REFERENCES person(id) ON DELETE RESTRICT ON UPDATE CASCADE,
	FOREIGN KEY (id_type) REFERENCES status_type(id) ON DELETE RESTRICT ON UPDATE CASCADE);

CREATE TABLE status_detail (
	id_detail BIGINT NOT NULL,
	id_status BIGINT NOT NULL,
	PRIMARY KEY (id_detail, id_status),
	FOREIGN KEY (id_detail) REFERENCES marked_detail(id) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (id_status) REFERENCES status(id) ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE operation (	
	id SMALLINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	title VARCHAR(255) NOT NULL UNIQUE);

CREATE TABLE qualification (
	id_person SMALLINT NOT NULL,
	id_operation SMALLINT NOT NULL,
	level TINYINT NOT NULL,
	PRIMARY KEY (id_person, id_operation),
	FOREIGN KEY (id_person) REFERENCES person(id) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (id_operation) REFERENCES operation(id) ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE route_sheet (
	id_entity BIGINT NOT NULL,
	number SMALLINT NOT NULL,
	duration INT NOT NULL,
	person_count TINYINT NOT NULL,
	id_operation SMALLINT NOT NULL,
	PRIMARY KEY (id_entity, number),
	FOREIGN KEY (id_entity) REFERENCES entity(id) ON DELETE RESTRICT ON UPDATE CASCADE,
	FOREIGN KEY (id_operation) REFERENCES operation(id) ON DELETE RESTRICT ON UPDATE CASCADE);

CREATE TABLE detail (
	id BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	id_entity BIGINT NOT NULL,
	state TINYINT NOT NULL,
	start_time DATETIME NOT NULL,
	finish_time DATETIME NOT NULL,
	id_parent BIGINT NULL,
	FOREIGN KEY (id_entity) REFERENCES entity(id) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (id_parent) REFERENCES detail(id) ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE person_time (
	id_person SMALLINT NOT NULL,
	start_time DATETIME NOT NULL,
	finish_time DATETIME NOT NULL,
	id_detail BIGINT NULL,
	id_entity BIGINT NULL,
	number SMALLINT NULL,
	UNIQUE(id_person, start_time),
	FOREIGN KEY (id_person) REFERENCES person(id) ON DELETE RESTRICT ON UPDATE CASCADE,
	FOREIGN KEY (id_entity, number) REFERENCES route_sheet(id_entity, number) ON DELETE RESTRICT ON UPDATE CASCADE,
	FOREIGN KEY (id_detail) REFERENCES detail(id) ON DELETE RESTRICT ON UPDATE CASCADE);

 DELIMITER $$
CREATE TRIGGER marking_cascade_delete BEFORE DELETE ON entity FOR EACH ROW
BEGIN
	DELETE FROM marking WHERE id IN (SELECT id_m FROM marking_line WHERE id_e = OLD.id);
END $$
 DELIMITER ;